-- =============================================
-- SEED ADMIN USER - Bootstrap First Admin Account
-- =============================================
-- This script creates the first admin user for local development.
-- It creates:
-- 1. An organization (if it doesn't exist)
-- 2. A stakeholder in the client database
-- 3. A UserAccount in the master database (auto-linked)
-- 
-- After running this, you can log in with:
-- Username: admin@hoanexus.local
-- Password: Admin123! (you'll be forced to change on first login)
-- =============================================

USE hoa_nexus_master;
GO

-- Step 1: Ensure test organization exists
-- =============================================
DECLARE @OrganizationID uniqueidentifier;
DECLARE @DatabaseName nvarchar(100) = 'hoa_nexus_testclient';

-- Get or create organization
IF NOT EXISTS (SELECT 1 FROM dbo.cor_Organizations WHERE DatabaseName = @DatabaseName)
BEGIN
    SET @OrganizationID = NEWID();
    INSERT INTO dbo.cor_Organizations 
        (OrganizationID, OrganizationName, DatabaseName, Subdomain, IsActive)
    VALUES
        (@OrganizationID, 'HOA Nexus Test Client', @DatabaseName, 'testclient', 1);
    PRINT 'Created test organization.';
END
ELSE
BEGIN
    SELECT @OrganizationID = OrganizationID FROM dbo.cor_Organizations WHERE DatabaseName = @DatabaseName;
    PRINT 'Test organization already exists.';
END
GO

-- Step 2: Create admin stakeholder in client database
-- =============================================
USE hoa_nexus_testclient;
GO

DECLARE @StakeholderID uniqueidentifier;
DECLARE @AdminEmail nvarchar(255) = 'admin@hoanexus.local';
DECLARE @AdminFirstName nvarchar(100) = 'Admin';
DECLARE @AdminLastName nvarchar(100) = 'User';

-- Check if admin stakeholder already exists
IF NOT EXISTS (SELECT 1 FROM dbo.cor_Stakeholders WHERE Email = @AdminEmail)
BEGIN
    SET @StakeholderID = NEWID();
    
    INSERT INTO dbo.cor_Stakeholders (
        StakeholderID, Type, SubType, AccessLevel, Department, Title,
        FirstName, LastName, Email, PortalAccessEnabled, IsActive
    )
    VALUES (
        @StakeholderID,
        'Company Employee',
        NULL,
        'Admin',
        'IT',
        'System Administrator',
        @AdminFirstName,
        @AdminLastName,
        @AdminEmail,
        1, -- PortalAccessEnabled
        1  -- IsActive
    );
    
    PRINT 'Created admin stakeholder in client database.';
    PRINT 'StakeholderID: ' + CAST(@StakeholderID AS nvarchar(36));
END
ELSE
BEGIN
    SELECT @StakeholderID = StakeholderID FROM dbo.cor_Stakeholders WHERE Email = @AdminEmail;
    PRINT 'Admin stakeholder already exists.';
END
GO

-- Step 3: Create UserAccount in master database
-- =============================================
USE hoa_nexus_master;
GO

DECLARE @StakeholderID uniqueidentifier;
DECLARE @OrganizationID uniqueidentifier;
DECLARE @AdminEmail nvarchar(255) = 'admin@hoanexus.local';
DECLARE @AdminFirstName nvarchar(100) = 'Admin';
DECLARE @AdminLastName nvarchar(100) = 'User';
DECLARE @TempPassword nvarchar(255) = 'Admin123!'; -- Temporary password (user must change on first login)

-- Get StakeholderID from client database
USE hoa_nexus_testclient;
SELECT @StakeholderID = StakeholderID FROM dbo.cor_Stakeholders WHERE Email = @AdminEmail;
USE hoa_nexus_master;

-- Get OrganizationID
SELECT @OrganizationID = OrganizationID FROM dbo.cor_Organizations WHERE DatabaseName = 'hoa_nexus_testclient';

-- Hash the password (using SQL Server's HASHBYTES - in production, backend uses bcrypt)
-- For now, we'll create it with a placeholder hash and the backend will handle password verification
-- Actually, we need to use bcrypt. Let me create a script that the backend can run instead.

-- Check if UserAccount already exists
IF NOT EXISTS (SELECT 1 FROM dbo.sec_UserAccounts WHERE Email = @AdminEmail)
BEGIN
    -- Note: PasswordHash needs to be generated by the backend using bcrypt
    -- For now, we'll insert with a placeholder and the user will need to reset password
    -- OR we can create an endpoint to do this properly
    
    PRINT '=============================================';
    PRINT 'IMPORTANT: UserAccount creation requires bcrypt password hashing.';
    PRINT 'Please use the backend API endpoint or run the Node.js seed script.';
    PRINT '=============================================';
    PRINT '';
    PRINT 'To create the admin user, you have two options:';
    PRINT '1. Use the backend API: POST /api/auth/bootstrap-admin';
    PRINT '2. Run: node backend/scripts/seed-admin-user.js';
    PRINT '';
    PRINT 'Admin credentials will be:';
    PRINT '  Email: ' + @AdminEmail;
    PRINT '  Password: ' + @TempPassword;
    PRINT '  (You will be forced to change password on first login)';
    PRINT '=============================================';
END
ELSE
BEGIN
    PRINT 'Admin UserAccount already exists.';
END
GO

